In [2]:
import numpy as np
from __future__ import print_function

In [7]:
import torch

Initializing a random Tensor:

In [5]:
torch.Tensor(5, 3)

tensor([[-2.9310e-22,  4.5897e-41,  4.4313e+10],
        [ 3.0653e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.6910e-03,  1.9621e-22,  1.9620e-22]])

Initiliazing a uniform Tensor:

In [6]:
torch.Tensor(5, 3).uniform_(-1, 1)

tensor([[-0.9404,  0.0303, -0.7689],
        [-0.5044, -0.7247, -0.3731],
        [ 0.8464,  0.7660, -0.2492],
        [-0.3902,  0.2938,  0.1748],
        [ 0.5673, -0.9034, -0.3458]])

Finding Shape of a Tensor:

In [10]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())

torch.Size([5, 3])


Tensor Types:

                Data type	    Tensor
    32-bit floating point	    torch.FloatTensor
    64-bit floating point	    torch.DoubleTensor
    16-bit floating point	    torch.HalfTensor
    8-bit integer(unsigned)	    torch.ByteTensor
    8-bit integer(signed)	    torch.CharTensor
    16-bit integer(signed)  	torch.ShortTensor
    32-bit integer(signed) 	    torch.IntTensor
    64-bit integer(signed) 	    torch.LongTensor

Using Lists and Numpy with Tensors:

In [12]:
z = torch.LongTensor([[1, 3], [2, 9]])
print(z)
print(z.type())
# Cast to numpy ndarray
print(z.numpy().dtype)

tensor([[ 1,  3],
        [ 2,  9]])
torch.LongTensor
int64


In [13]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


Mathematical Operations:

In [16]:
y = x * torch.randn(5, 3)
print(y)

tensor([[-0.1076, -0.0366, -0.3092],
        [ 1.0317, -0.1807,  0.0080],
        [ 1.8711,  0.9633, -1.0408],
        [ 0.1052, -0.4743,  0.4558],
        [-0.1653,  0.5107,  0.3618]])


In [17]:
y = x / torch.sqrt(torch.randn(5, 3) ** 2)
print(y)

tensor([[-0.2405, -0.3196, -0.8152],
        [ 0.9448, -0.5920, -0.0388],
        [-2.2806, -0.6756, -0.6995],
        [-0.8239,  0.4762, -0.3711],
        [-0.7190,  1.5459, -1.1646]])


Broadcasting:

In [18]:
print (x.size())
y = x + torch.randn(5, 1)
print(y)

torch.Size([5, 3])
tensor([[-0.1480, -0.1069, -0.5824],
        [ 1.9699,  0.7082,  1.0121],
        [-1.0140, -1.0067, -0.6517],
        [ 1.2993,  2.6219,  1.5082],
        [ 0.4560,  1.9668,  0.1091]])


Reshape:

In [19]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).size())  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).size()) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).squeeze().size())
# If input is of shape: (Ax1xBxCx1xD)(Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)(AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


Repeat:

In [20]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


Concatenate:

In [21]:
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])


Advanced Indexing:

In [25]:
y = torch.randn(2, 3, 4)
print(y)
print(y[[1, 0, 1, 1]])
print(y[[1, 0, 1, 1]].size())

# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(rev_idx)
print(y[rev_idx])
print(y[rev_idx].size())

tensor([[[-1.4979, -0.4892, -0.4186,  0.9151],
         [ 0.0378,  0.2536,  0.7040, -0.5281],
         [-0.5470, -0.7903,  0.2602,  0.1899]],

        [[ 1.1646,  1.5807,  0.4921, -0.2455],
         [-0.4227,  0.7815,  2.1059, -0.0832],
         [-1.6229,  1.1339,  0.2441,  0.7954]]])
tensor([[[ 1.1646,  1.5807,  0.4921, -0.2455],
         [-0.4227,  0.7815,  2.1059, -0.0832],
         [-1.6229,  1.1339,  0.2441,  0.7954]],

        [[-1.4979, -0.4892, -0.4186,  0.9151],
         [ 0.0378,  0.2536,  0.7040, -0.5281],
         [-0.5470, -0.7903,  0.2602,  0.1899]],

        [[ 1.1646,  1.5807,  0.4921, -0.2455],
         [-0.4227,  0.7815,  2.1059, -0.0832],
         [-1.6229,  1.1339,  0.2441,  0.7954]],

        [[ 1.1646,  1.5807,  0.4921, -0.2455],
         [-0.4227,  0.7815,  2.1059, -0.0832],
         [-1.6229,  1.1339,  0.2441,  0.7954]]])
torch.Size([4, 3, 4])
tensor([ 1,  0])
tensor([[[ 1.1646,  1.5807,  0.4921, -0.2455],
         [-0.4227,  0.7815,  2.1059, -0.0832],
         

Matrix Multiplication:

In [ ]:
x = torch.cuda.HalfTensor(5, 3).uniform_(-1, 1)
y = torch.cuda.HalfTensor(3, 5).uniform_(-1, 1)
torch.matmul(x, y)

Moving Tensors from CPU -> GPU:

In [ ]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
x = x.cpu()
print(x)

Contiguity in Memory:

In [ ]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))